M48
; DRILL file {KiCad 8.0.0} date 2024-03-30T16:18:12+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-30T16:18:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X91.713Y-84.916
X91.713Y-93.316
X91.975Y-75.9
X141.912Y-143.5
T2
X90.6Y-55.6
X90.6Y-144.4
X179.6Y-55.4
X179.6Y-105.6
M30
